# Generated by Django 2.1.7 on 2019-03-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='tb_users',
        ),
    ]
